# Copyright 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

# Usage: certificates.yml
temp_download_dir: "/tmp"
omnia_dir: "/opt/omnia"
nerdctl_registry_dir: "{{ omnia_dir }}/nerdctl-registry"
nerdctl_registry_certs_dir: "{{ nerdctl_registry_dir }}/certs"
nerdctl_registry_data_dir: "{{ nerdctl_registry_dir }}/images"
openssl_key_path: "{{ nerdctl_registry_certs_dir }}/domain.key"
openssl_cert_path: "{{ nerdctl_registry_certs_dir }}/domain.crt"
openssl_csr_path: "{{ nerdctl_registry_certs_dir }}/domain.csr"
private_key_size: "4096"
csr_common_name: "private_registry"
certificate_provider: "selfsigned"

# Usage: initiate_private_registry.yml
nerdctl_registry_path:
  - { src: "nerdctl-registry.j2", dest: "{{ nerdctl_registry_dir }}/nerdctl-registry" }
  - { src: "nerdctl-registry.service.j2", dest: "/etc/systemd/system/nerdctl-registry.service" }
omnia_registry_failure_msg: "omnia-registry container could not be started"
nerdctl_registry_enable_fail_msg: "Failed to initiate nerdctl-registry service. This may be due to a Docker pull issue or insuffecient proxy details. If you are behind a proxy, please ensure that the necessary proxy details are provided in the input/site_config.yml file."   # noqa: yaml[line-length]
containerd_certs_dir: "/etc/containerd/certs.d"
nerdctl_registry_port: 5001
directory_permissions: "0755"
file_permission: "0644"
hosts_file: "/etc/hosts"
registry_wait_time: "10"
registry_wait_msg: "Waiting for nerdctl registry to be created..."
retry_count: "5"
delay_time: "10"

# Usage: main.yml
oim_os_redhat: "redhat"
oim_os_rocky: "rocky"
oim_os_ubuntu: "ubuntu"

# Usage: set_environment.yml
environment_file_path: "{{ role_path }}/templates/omnia_environment.j2"
omnia_environment_path: "/etc/omnia_environment"

# Usage: docker_login.yml
docker_login_fail_msg: "Docker login failed. Please ensure the docker login credentials in the input/provision_config_credentials.yml are valid.
If they are, this error can occur due to a pull limit issue or multiple requests. Please try running the playbook again after waiting for a while."
