#  Copyright 2022 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Get the hostname
  ansible.builtin.command: hostname
  register: machine_hostname
  changed_when: true

- name: Get the short hostname
  ansible.builtin.command: hostname -s
  register: short_hostname
  changed_when: false

- name: Set facts for node hostname and ip
  ansible.builtin.set_fact:
    node_ip: "{{ inventory_hostname }}"
    node_hostname: "{{ machine_hostname.stdout }}"
    node_name: "{{ short_hostname.stdout }}"

- name: Add host name in hosts file
  ansible.builtin.lineinfile:
    dest: "{{ hosts_file_dest }}"
    line: "{{ inventory_hostname }} {{ machine_hostname.stdout }} {{ short_hostname.stdout }}"
    state: present
    create: yes
    mode: "{{ hosts_file_mode }}"

- name: Add compute and login node info in manager node hosts file
  when: "'manager' in group_names"
  block:
    - name: Add compute hosts info in manager node hosts file
      ansible.builtin.lineinfile:
        dest: "{{ hosts_file_dest }}"
        line: "{{ hostvars[item].node_ip }} {{ hostvars[item].node_hostname }} {{ hostvars[item].node_name }}"
        state: present
        create: yes
        mode: "{{ hosts_file_mode }}"
      with_items:
        - "{{ groups['compute'] }}"

    - name: Add login node info in /etc/hosts of manager node
      ansible.builtin.lineinfile:
        dest: "{{ hosts_file_dest }}"
        line: "{{ hostvars[item].node_ip }} {{ hostvars[item].node_hostname }} {{ hostvars[item].node_name }}"
        state: present
        create: yes
        mode: "{{ hosts_file_mode }}"
      with_items:
        - "{{ groups['login'] }}"
      when: hostvars["127.0.0.1"]["login_node_required"]
  rescue:
    - name: Updating manager hosts file failed
      ansible.builtin.fail:
        msg: "{{ manager_hosts_update_fail_msg }}"

- name: Add manager and login node info in compute node hosts file
  when: "'compute' in group_names"
  block:
    - name: Add manager hosts info in compute node hosts file
      ansible.builtin.lineinfile:
        dest: "{{ hosts_file_dest }}"
        line: "{{ hostvars[item].node_ip }} {{ hostvars[item].node_hostname }} {{ hostvars[item].node_name }}"
        state: present
        create: yes
        mode: "{{ hosts_file_mode }}"
      with_items:
        - "{{ groups['manager'] }}"

    - name: Add compute info in /etc/hosts of compute nodes
      ansible.builtin.lineinfile:
        dest: "{{ hosts_file_dest }}"
        line: "{{ hostvars[item.1].node_ip }} {{ hostvars[item.1].node_hostname }} {{ hostvars[item.1].node_name }}"
        state: present
        create: yes
        mode: "{{ hosts_file_mode }}"
      with_nested:
        - "{{ groups['compute'] }}"
        - "{{ groups['compute'] }}"

    - name: Add login node info in /etc/hosts of compute nodes
      ansible.builtin.lineinfile:
        dest: "{{ hosts_file_dest }}"
        line: "{{ hostvars[item].node_ip }} {{ hostvars[item].node_hostname }} {{ hostvars[item].node_name }}"
        state: present
        create: yes
        mode: "{{ hosts_file_mode }}"
      with_items:
        - "{{ groups['login'] }}"
      when: hostvars["127.0.0.1"]["login_node_required"]
  rescue:
    - name: Updating compute hosts file failed
      ansible.builtin.fail:
        msg: "{{ compute_hosts_update_fail_msg }}"

- name: Add manager and compute nodes info in login node hosts file
  when: 
    - "'login' in group_names"
    - hostvars["127.0.0.1"]["login_node_required"]
  block:
    - name: Add manager info in /etc/hosts of login node
      ansible.builtin.lineinfile:
        dest: "{{ hosts_file_dest }}"
        line: "{{ hostvars[item].node_ip }} {{ hostvars[item].node_hostname }} {{ hostvars[item].node_name }}"
        state: present
        create: yes
        mode: "{{ hosts_file_mode }}"
      with_items:
        - "{{ groups['manager'] }}"

    - name: Add compute info in /etc/hosts of login node
      ansible.builtin.lineinfile:
        dest: "{{ hosts_file_dest }}"
        line: "{{ hostvars[item].node_ip }} {{ hostvars[item].node_hostname }} {{ hostvars[item].node_name }}"
        state: present
        create: yes
        mode: "{{ hosts_file_mode }}"
      with_items:
        - "{{ groups['compute'] }}"
  rescue:
    - name: Updating login hosts file failed
      ansible.builtin.fail:
        msg: "{{ login_hosts_update_fail_msg }}"
