#  Copyright 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Give slurm user permission to slurmd spool
  ansible.builtin.file:
    path: "{{ spool_slurmd_pth }}"
    owner: slurm
    group: slurm
    mode: "{{ tmp_mode }}"
    state: touch

- name: Create log files on slurm nodes
  ansible.builtin.file:
    path: "{{ slurm_logpth }}"
    owner: slurm
    group: slurm
    mode: "{{ tmp_mode }}"
    state: touch
  with_items:
    - slurmd.log

- name: Install ufw
  ansible.builtin.package:
    name: "{{ ufw_package }}"
    state: present
  tags: firewall

- name: Ensure UFW is enabled and set to start on boot
  community.general.ufw:
    state: enabled
    policy: allow
  tags: firewall

- name: Allow SSH port
  community.general.ufw:
    rule: allow
    name: OpenSSH
  tags: firewall

- name: Allow specific TCP ports for SLURM
  community.general.ufw:
    rule: allow
    port: "{{ item.split('/')[0] }}"
    proto: "{{ item.split('/')[1] }}"
  loop:
    - "{{ tcp_port1 }}"
    - "{{ tcp_port2 }}"
    - "{{ tcp_port3 }}"
    - "{{ udp_port1 }}"
    - "{{ udp_port2 }}"
    - "{{ udp_port3 }}"
  tags: firewall

- name: Allow SLURM dynamic port range for srun
  community.general.ufw:
    rule: allow
    proto: tcp
    port: "{{ srun_port }}"
  tags: firewall

- name: Reload ufw to apply changes
  ansible.builtin.command: ufw reload
  changed_when: true
  tags: firewall

- name: Delete slurm.conf file from default path
  ansible.builtin.file:
    path: "{{ slurm_conf_default_path }}"
    state: absent
    force: true
