#  Copyright 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---


- name: Install packages for slurm
  when: ansible_distribution | lower is in ['redhat', 'rocky']
  block:
    - name: Configure dnf.conf
      ansible.builtin.replace:
        path: "{{ dnf_conf_path }}"
        regexp: '^exclude='
        replace: '#exclude='

    - name: Update the yum repos cache
      ansible.builtin.command: dnf makecache
      changed_when: true

    - name: Install slurm packages
      ansible.builtin.shell: dnf install -y --installroot={{ slurm_nfs_folder }} slurm-slurmctld slurm-slurmdbd # noqa: command-instead-of-shell
      become: true
      failed_when: false
      changed_when: false
      tags: install
  always:
    - name: Revert dnf.conf
      ansible.builtin.replace:
        path: "{{ dnf_conf_path }}"
        regexp: '^#exclude='
        replace: 'exclude='

    - name: Update the yum repos cache
      ansible.builtin.command: dnf makecache
      changed_when: true

- name: Install packages for slurm
  when: ansible_distribution | lower == "ubuntu"
  block:
    - name: Update package list
      ansible.builtin.apt:
        update_cache: true

    - name: Install packages for slurm
      ansible.builtin.apt:
        name: "{{ slurm_packages_ubuntu }}"
        state: present
      failed_when: false
      changed_when: false
      tags: install
