#  Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Install firewalld
  ansible.builtin.package:
    name: firewalld
    state: present
  tags: firewalld

- name: Start and enable firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true
  tags: firewalld

- name: Configure firewall rules for Slurm - TCP/UDP ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    zone: public
    permanent: true
    state: enabled
  loop:
    - "{{ tcp_port1 }}"
    - "{{ tcp_port2 }}"
    - "{{ tcp_port3 }}"
    - "{{ tcp_port4 }}"
    - "{{ tcp_port5 }}"
    - "{{ udp_port1 }}"
    - "{{ udp_port2 }}"
    - "{{ udp_port3 }}"
    - "{{ udp_port4 }}"
  when: "'slurm_control_node' in group_names"
  tags: firewalld

- name: Get network address and subnet mask
  ansible.builtin.set_fact:
    network_address: "{{ (ansible_default_ipv4.network + '/' + ansible_default_ipv4.netmask) | ansible.utils.ipaddr('network/prefix') }}"
  tags: firewalld

- name: Allow all incoming traffic on internal network for Slurm
  ansible.posix.firewalld:
    rich_rule: "rule family='ipv4' source address='{{ network_address }}' accept"
    zone: public
    permanent: true
    state: enabled
  tags: firewalld

- name: Reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded
  tags: firewalld
