#  Copyright 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---
- name: Set bash_rc_path for Ubuntu
  ansible.builtin.set_fact:
    bashrc_path_final: "{{ bashrc_path_ubuntu }}"
  when: ansible_distribution | lower == 'ubuntu'

- name: Set bash_rc_path for non-Ubuntu
  ansible.builtin.set_fact:
    bashrc_path_final: "{{ bashrc_path }}"
  when: ansible_distribution | lower is in ['redhat', 'rocky']

- name: Check if environment variables are set
  ansible.builtin.command: echo $SLURM_CONF
  changed_when: false
  failed_when: false
  register: path_output

- name: Check if environment variables are set
  ansible.builtin.command: echo $SLURM_CONF
  changed_when: false
  failed_when: false
  register: path_output

- name: Set environment variable for SLURM_CONF
  when: "'slurm' not in path_output.stdout"
  block:
    - name: Check current environment variables
      ansible.builtin.shell: echo $SLURM_CONF
      changed_when: false
      register: environment_output

    - name: Replace SLURM_CONF variable
      ansible.builtin.lineinfile:
        path: "{{ bashrc_path_final }}"
        regexp: '^SLURM_CONF=*'
        insertafter: EOF
        line: 'export SLURM_CONF={{ slurm_nfs_folder }}/etc/slurm/slurm.conf'

- name: Source /etc/bashrc
  ansible.builtin.shell: source  "{{ bashrc_path }}" # noqa: command-instead-of-shell
  changed_when: false
  when: ansible_distribution | lower is in ['redhat', 'rocky']

- name: Cgroup configuration - cgroup.conf
  ansible.builtin.template:
    src: "{{ cgroup_conf_template }}"
    dest: "{{ slurm_nfs_folder }}/etc/slurm/cgroup.conf"
    mode: "{{ cgroup_mode }}"
  when: ansible_distribution | lower == "ubuntu"

- name: Create symbolic link for cgroup.conf
  ansible.builtin.file:
    src: "{{ slurm_nfs_folder }}/etc/slurm/cgroup.conf"
    dest: "{{ nfs_slurm_main_dest }}/cgroup.conf"
    state: link
    force: true
  when: ansible_distribution | lower == "ubuntu"

- name: Source /etc/bashrc
  ansible.builtin.shell: "bash -i -c 'source {{ bashrc_path_ubuntu }}'" # noqa: command-instead-of-shell
  changed_when: false
  when: ansible_distribution | lower == "ubuntu"
