#  Copyright 2023 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Copy oneapi repo
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items: "{{ oneapi_repo_path }}"

- name: Downloading intel packages
  block:
    - name: Download intel packages(This might take 10-15 minutes)
      ansible.builtin.command: dnf download {{ item }} -y --resolve --alldeps --destdir="{{ omnia_common_xcat_repo }}"
      changed_when: true
      with_items: "{{ intel_packages }}"
  rescue:
    - name: Failed - Downloading intel packages failed
      ansible.builtin.fail:
        msg: "{{ download_intel_package_fail_msg }}"

- name: Build omnia repo
  ansible.builtin.command: createrepo {{ other_pkg_dir }}/omnia
  changed_when: true
