# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
chrony_servers:
  - 2.centos.pool.ntp.org
cluster_name: cluster
slurm_uid: 6001
slurm_user: slurm
slurm_user_group: slurm
# share_path: "{{ share_mounted_path }}"
share_path: "{{ nfs_client_params | selectattr('slurm_share', 'equalto', true) | map(attribute='client_share_path') | first }}"
slurm_share_prefix: ""
slurm_config_dir: /etc/slurm
slurm_dir_name: slurm
slurm_dbd_port: 6819
slurm_db_port_default: 3306
slurm_db_type_default: mariadb
slurm_db_username_default: root
slurm_db_password_default: ""
slurm_dbd_db_username: "{{ slurm_user }}"
slurm_dbd_db_password: slurmPassword123!
slurm_db_login_unix_socket: /var/lib/mysql/mysql.sock
slurm_mysql_cnf_path: /etc/my.cnf.d/mysql-server.cnf
slurm_mariadb_cnf_path: /etc/my.cnf.d/mariadb-server.cnf
slurm_munge_key_path: "{{ share_path }}/{{ slurm_dir_name }}/munge.key"
slurm_partition_name: normal
slurm_ctld_parameters: []
partitions: {}
_clean_before_install: false
conf_file_mode: "0644"
slurm_mode: "0644"
munge_mode: "0400"
common_mode: "0755"
slurm_dbd_mode: "0600"
common_packages:
  RedHat:
    - firewalld
    - python3-firewall
munge_packages:
  RedHat:
    - munge
slurm_controller_packages:
  RedHat:
    - slurm-slurmctld
slurm_compute_packages:
  RedHat:
    - slurm-slurmd
slurm_login_packages:
  RedHat:
    - slurm
slurm_dbd_packages:
  RedHat:
    - slurm-slurmdbd
db_packages:
  RedHat:
    mysql:
      - python3-PyMySQL
      - mysql-server
    mariadb:
      - python3-PyMySQL
      - mariadb-server

# messages
inv_validation_fail_msg: "Failed. slurm_control_node and slurm_node groups should be defined in inventory and should have at least one node provided."
intersect_validation_fail_msg: "Failed. Node mentioned in slurm_control_node group should not be part of slurm_node or login group"
