---
# vars file for slurm
chrony_servers:
  - 2.centos.pool.ntp.org
cluster_name: cluster
slurm_uid: 6001
slurm_user: slurm
slurm_user_group: slurm
share_path: "{{ share_mounted_path }}"
slurm_share_prefix: ""
slurm_config_dir: /etc/slurm
slurm_dir_name: slurm
slurm_dbd_port: 6819
db_port_default: 3306
db_type_default: mariadb
db_username_default: root
db_password_default: password
slurm_db_username: "{{ slurm_user }}"
slurm_db_password: slurmPassword123!
slurm_munge_key_path: "{{ share_path }}/{{ slurm_dir_name }}/munge.key"
slurm_partition_name: normal
slurm_ctld_parameters: []
partitions: {}
_clean_before_install: false
conf_file_mode: "0644"
slurm_mode: "0644"
munge_mode: "0400"
common_mode: "0755"
slurm_dbd_mode: "0600"
common_packages:
  RedHat:
    - firewalld
    - python3-firewall
munge_packages:
  RedHat:
    - munge
slurm_controller_packages:
  RedHat:
    - slurm-slurmctld
slurm_compute_packages:
  RedHat:
    - slurm-slurmd
slurm_login_packages:
  RedHat:
    - slurm
slurm_dbd_packages:
  RedHat:
    - slurm-slurmdbd
db_packages:
  RedHat:
    mysql:
      - python3-PyMySQL
      - mysql-server
    mariadb:
      - python3-PyMySQL
      - mariadb-server

# messages
inv_validation_fail_msg: "Failed. slurm_control_node and slurm_node groups should be defined in inventory and should have at least one node provided."
intersect_validation_fail_msg: "Failed. Node mentioned in slurm_control_node group should not be part of slurm_node or login group"
