# Include omnia_config_credentials.yml
- name: Include omnia_config_credentials.yml
  block:
    - name: Check omnia_credential file is encrypted
      ansible.builtin.command: cat {{ omnia_credential_file }}
      changed_when: false
      register: omnia_credential_file_content
      no_log: true
      tags: init

    - name: Decrpyt omnia_credential.yml
      ansible.builtin.command: >-
        ansible-vault decrypt {{ omnia_credential_file }}
        --vault-password-file {{ omnia_credential_vault_path }}
      changed_when: false
      when: ansible_vault_search_key in omnia_credential_file_content.stdout
      tags: init

    - name: Include omnia_credentials.yml
      ansible.builtin.include_vars: "{{ omnia_credential_file }}"
      register: include_provision_cred_config
      no_log: true
      tags: init
  rescue:
    - name: Failed to include omnia_credentials.yml
      ansible.builtin.fail:
        msg: "Failed to include omnia_credentials.yml"

- name: debug postgress password
  debug:
    msg: "{{ postgress_password }}"