# Include omnia_config_credentials.yml
- name: Include omnia_config_credentials.yml
  block:
    - name: Decrpyt omnia_config_credential.yml
      ansible.builtin.command: >-
        ansible-vault decrypt {{ omnia_credential_file }}
        --vault-password-file {{ omnia_credential_vault_path }}
      changed_when: false
      tags: init

    - name: Include omnia_config_credentials.yml
      ansible.builtin.include_vars: "{{ omnia_credential_file }}"
      register: include_omnia_cred_config
      no_log: true
      tags: init
  rescue:
    - name: Failed to include omnia_config_credentials.yml
      ansible.builtin.fail:
        msg: "{{ omnia_credential_syntax_fail_msg }} Error: {{ include_omnia_cred_config.message }}"
  
    - name: Encrypt omnia_config_credentials.yml
      ansible.builtin.command: >-
        ansible-vault encrypt {{ omnia_credential_file }}
        --vault-password-file {{ omnia_credential_vault_path }}
      changed_when: false
      tags: init

- name: Encrypt omnia_config_credentials.yml
  ansible.builtin.command: >-
    ansible-vault encrypt {{ omnia_credential_file }}
    --vault-password-file {{ omnia_credential_vault_path }}
  changed_when: false
  tags: init

