# Copyright 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---


# Usage: include_provision_config.yml
provision_config_file: "{{ role_path }}/../../../input/provision_config.yml"
fail_msg_provision_config_file: "provision_config.yml file doesn't exist."
fail_timezone_msg: "Failed. Incorrect timezone provided. Please check the file timezone.txt in discovery/roles/discovery_validations/common/files/ folder."

telemetry_config_file: "{{ role_path }}/../../../input/telemetry_config.yml"
telemetry_namespace: "telemetry-and-visualizations"
vault_filename: "{{ role_path }}/../../../input/.telemetry_vault_key"
vault_file_perm: '0644'
idrac_telemetry_pod: "idrac-telemetry"
tsdb_pod: "timescaledb"
timescaledb_name: "telemetry_metrics"
mysqldb_pod: "mysqldb"
mysqldb_table: "idrac_telemetrysource_services_db.services"
python_pip_packages:
  - omsdk==1.2.513
  - pysnmp==6.1.3

# Usage: k8s_secrets.yml
# namespace: telemetry-and-visualizations
secrets_name: credentials
mysqldb_secrets_name: mysqldb-credentials

timescaledb_role_path: "{{ playbook_dir }}/../telemetry/roles/timescaledb"
timezone_file_path: "{{ playbook_dir }}/../telemetry/roles/telemetry_validation/files/timezone.txt"
idrac_deployment_file: "{{ role_path }}/../../../telemetry/roles/idrac_telemetry/tasks/idrac_telemetry_deployment.yml"
k8s_backup_location: "{{ backup_location }}/k8s"
timescale_telemetry_backup_file: "telemetry_tsdb_dump.sql"
idrac_reference_tools_folder: "{{ mount_location }}/iDRAC-Telemetry-Reference-Tools"

python_version: "{{ ansible_python_interpreter }}"
db_schema_utility: "{{ role_path }}/../../../telemetry/roles/omnia_telemetry_prepare_oim/files/omnia_telemetry_schema_creation.py"
timescaledb_container_port: 5432

# Usage: reconfig_timescaledb_data.yml
idrac_telemetry_path: "/go/src/github.com/telemetry-reference-tools/omnia_timescaledb.tar.gz"
postgresql_pod_data: "/var/lib/postgresql/data"
timescaledb_mnt: "{{ mount_location }}/timescaledb"
timescaledb_mnt_tar: "{{ mount_location }}/timescaledb/omnia_timescaledb.tar.gz"
idrac_mnt_tar: "{{ mount_location }}/iDRAC-Telemetry-Reference-Tools/omnia_timescaledb.tar.gz"
timescaledb_container_volume_mount: "/spec/template/spec/containers/0/volumeMounts/1/mountPath"
timescaledb_host_mount: "/var/lib/postgresql/data"
backup_tsdb_tar: "{{ k8s_backup_location }}/omnia_timescaledb.tar.gz"
file_mode: "0644"
database_name: "telemetry_metrics"
timescaledb_k8s_name: timescaledb
retry_count: 5
delay_pod: 30
