#  Copyright 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Load and parse telemetry.json
  ansible.builtin.set_fact:
    telemetry: "{{ lookup('file', telemetry_json_path) | from_json }}"

- name: Extract docker-ce-cli package version from json file
  block:
    - name: Extract docker-ce-cli version
      ansible.builtin.set_fact:
        docker_version: "{{ (telemetry.telemetry.cluster | selectattr('package', 'match', '^docker-ce-cli-') | map(attribute='package') | first).split('-')[3] }}"  # noqa: yaml[line-length]

  rescue:
    - name: Display message if docker-ce-cli package is not found
      ansible.builtin.fail:
        msg: "{{ redhat_docker_package_missing }}"

- name: Add Docker CE repository for RHEL
  ansible.builtin.command: yum-config-manager --add-repo "{{ docker_repo }}"
  changed_when: false

- name: Install Docker packages
  ansible.builtin.package:
    name: "{{ docker_packages_redhat }}"
    state: present

- name: Start Docker Service
  ansible.builtin.systemd:
    name: docker
    state: restarted
  register: docker_result
  until: docker_result is succeeded
  retries: "{{ package_retry }}"
  delay: "{{ delay_time }}"

- name: Configure proxy environment variables for docker
  ansible.builtin.include_tasks: configure_docker_proxy.yml
  when: proxy_status

- name: Login to docker when credentials are given
  ansible.builtin.include_tasks: docker_login.yml
  when: docker_login
