# Copyright 2025 Intel Corporation. All Rights Reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This script facilitates the fine-tuning of the Llama 3.1 8B model
# across one, two, or multiple nodes by adjusting the number of MPI worker replicas.
# It utilizes the DeepSpeed no-SSH implementation.

---
apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: gaudi-llm-ds-ft-multi-8b-no-ssh
  namespace: workloads
spec:
  slotsPerWorker: 8
  runPolicy:
    cleanPodPolicy: Running
  launcherCreationPolicy: WaitForWorkersReady
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
            - image: vault.habana.ai/gaudi-docker/1.19.2/ubuntu24.04/habanalabs/pytorch-installer-2.5.1:latest
              name: gaudi-llm-ds-ft-multi-8b-no-ssh-launcher
              env:
                - name: HF_HOME
                  value: "/root/.cache/huggingface"
                - name: no_proxy
                  value: "localhost,127.0.0.1"
                - name: LLM_MODEL
                  value: meta-llama/Meta-Llama-3.1-8B-Instruct
                - name: NUM_HPU
                  value: "8"
                - name: NUM_EPOCHS
                  value: "3"
                - name: HUGGING_FACE_HUB_TOKEN
                  value: ""
                - name: http_proxy
                  value: ""
                - name: https_proxy
                  value: ""
                - name: no_proxy
                  value: ""
              command: ["/bin/bash", "-c"]
              args:
                - >-
                  /usr/bin/ssh-keygen -A;
                  echo "    KexAlgorithms curve25519-sha256,sntrup761x25519-sha512@openssh.com" |  tee -a /etc/ssh/ssh_config;
                  /usr/sbin/sshd;

                  HOSTSFILE=$OMPI_MCA_orte_default_hostfile;
                  MASTER_ADDR="$(head -n 1 $HOSTSFILE | sed -n s/[[:space:]]slots.*//p)";
                  SETUP_CMD="git clone  https://github.com/huggingface/optimum-habana /optimum-habana";
                  export no_proxy=$no_proxy,$KUBERNETES_SERVICE_HOST;
                  NUM_NODES=$(wc -l < $HOSTSFILE);
                  N_CARDS=$((NUM_NODES*NUM_HPU));

                  JOBHOSTFILE=/root/.cache/hostfile_$(date +"%Y%m%d_%H%M%S");
                  tee "$JOBHOSTFILE" < "$HOSTSFILE";

                  mpirun --npernode 1 \
                    --tag-output \
                    --allow-run-as-root \
                    --prefix $MPI_ROOT \
                    --bind-to socket \
                    --report-bindings \
                    --merge-stderr-to-stdout  \
                    -x RDMAV_FORK_SAFE=1 \
                    -x FI_EFA_USE_DEVICE_RDMA=1 \
                    -x PMIX_RANK \
                    -x http_proxy=$http_proxy \
                    -x https_proxy=$https_proxy \
                    -x no_proxy=$no_proxy \
                    -x LLM_MODEL=$LLM_MODEL \
                    -x NUM_EPOCHS=$NUM_EPOCHS \
                    -x JOBHOSTFILE=$JOBHOSTFILE \
                    -x master_addr=$MASTER_ADDR \
                    -x HF_HOME=$HF_HOME \
                    -x PT_HPU_MAX_COMPOUND_OP_SIZE=10 \
                    -x PT_HPU_MAX_COMPOUND_OP_SYNC=1 \
                    -x DEEPSPEED_HPU_ZERO3_SYNC_MARK_STEP_REQUIRED=1 \
                    -x NUM_HPU=$NUM_HPU \
                    -x HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN \
                    bash -i -c '
                    git clone  https://github.com/huggingface/optimum-habana /optimum-habana
                    cd /optimum-habana
                    git checkout v1.15.0

                    pip install .
                    pip install -r examples/language-modeling/requirements.txt
                    pip install git+https://github.com/HabanaAI/DeepSpeed.git@1.20.0

                    cd examples/language-modeling/

                    echo "Starting the test"

                    unset OMPI_COMM_WORLD_LOCAL_RANK
                    echo $OMPI_COMM_WORLD_LOCAL_RANK

                    echo "starting the command"
                    /usr/bin/python3 /usr/local/bin/deepspeed --hostfile=$JOBHOSTFILE  --no_local_rank  --master_addr=$master_addr --no_ssh --master_port=29500 --node_rank=$PMIX_RANK  run_lora_clm.py --model_name_or_path $LLM_MODEL --dataset_name tatsu-lab/alpaca --bf16 True  --output_dir ./model_lora_llama_ddp  --num_train_epochs $NUM_EPOCHS --per_device_train_batch_size 8  --gradient_accumulation_steps 2  --evaluation_strategy "no"  --save_strategy "no"  --learning_rate 3e-4   --warmup_ratio  0.03  --lr_scheduler_type "constant"  --logging_steps 1  --do_train   --do_eval --use_habana  --use_lazy_mode  --throughput_warmup_steps 3 --lora_rank=8 --lora_alpha=16  --lora_dropout=0.05  --lora_target_modules "q_proj" "v_proj" --dataset_concatenation  --max_seq_length 512  --ddp_bucket_cap_mb 50  --adam_epsilon 1e-08  --validation_split_percentage 4 --low_cpu_mem_usage False

                  ';
                  cat $JOBHOSTFILE;
                  rm $JOBHOSTFILE;
                  echo "Host file removed successfully";

              volumeMounts:
                - name: datasets
                  mountPath: /root/.cache
          volumes:
            - name: datasets
              persistentVolumeClaim:
                claimName: shared-model
                readOnly: false
    Worker:
      replicas: 1
      template:
        spec:
          hostIPC: true
          containers:
            - image: vault.habana.ai/gaudi-docker/1.19.2/ubuntu24.04/habanalabs/pytorch-installer-2.5.1:latest
              name: gaudi-llm-ds-ft-multi-8b-no-ssh-worker
              command: ["/bin/bash", "-c"]
              args:
                - >-
                  /usr/bin/ssh-keygen -A;
                  /usr/sbin/sshd;
                  sleep 365d;
              resources:
                limits:
                  habana.ai/gaudi: 8
                  memory: 250Gi
                  hugepages-2Mi: 9800Mi
                requests:
                  habana.ai/gaudi: 8
                  memory: 250Gi
                  hugepages-2Mi: 9800Mi
              volumeMounts:
                - name: datasets
                  mountPath: /root/.cache
          volumes:
            - name: datasets
              persistentVolumeClaim:
                claimName: shared-model
                readOnly: false
