# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Fetch "{{ password }}" if empty
  when: vars[password] is defined and (vars[password] | length == 0)
  block:
    - name: Prompt user for password
      pause:
        prompt: "Enter {{ password }}"
        echo: no
      register: password_input

    - name: Prompt user to confirm password
      pause:
        prompt: "Confirm {{ password }}"
        echo: no
      register: confirm_password

    - name: Ensure passwords match
      fail:
        msg: "Passwords do not match! Please try again."
      when: password_input.user_input != confirm_password.user_input

    - name: Update vars file with entered password
      lineinfile:
        path: "{{ omnia_credential_file }}"
        regexp: '^{{ password }}:'
        line: "{{ password }}: \"{{ password_input.user_input }}\""