---
- name: "Upgrading k8s cluster version to {{ k8s_upgrade_version }}"
  ansible.builtin.include_tasks: manager-upgrade.yml
  loop: "{{ k8s_versions }}"
  when:
    - item | int <= k8s_upgrade_version | int
