#  Copyright 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Read software_config.json
  ansible.builtin.include_vars:
    file: "{{ software_config_file }}"
    name: software_config

- name: Get cluster_os_type from software_config.json
  ansible.builtin.set_fact:
    cluster_os_type: "{{ software_config['cluster_os_type'] }}"

- name: Get cluster_os_version from software_config.json
  ansible.builtin.set_fact:
    cluster_os_version: "{{ software_config['cluster_os_version'] }}"

- name: Load telemetry.json
  ansible.builtin.set_fact:
    telemetry_json: "{{ lookup('file', telemetry_json_file) | from_json }}"

- name: Load the vars from telemetry file
  ansible.builtin.set_fact:
    telemetry_package_map: "{{ telemetry_package_map | default({}) | combine({((item.package).rsplit('-', 1)[0]): item.package}) }}"
  loop: "{{ telemetry_json['telemetry']['cluster'] }}"
  when: (item.type == "tarball" or item.type == "git")

- name: Extract k8s version
  ansible.builtin.set_fact:
    k8s_version: "{{ (telemetry_package_map['kubectl']).rsplit('-', 1)[1] | default('1.26.12') }}"

- name: Gather all IP addresses
  ansible.builtin.command: ip -4 addr show
  register: ip_output
  changed_when: false

- name: Read Omnia Infrastructure Manager hostname
  ansible.builtin.command: hostname
  changed_when: false
  register: hostname_output

- name: Read Omnia Infrastructure Manager domain name
  ansible.builtin.command: hostname -d
  changed_when: false
  register: domain_name_output

- name: Set oim details
  ansible.builtin.set_fact:
    oim_hostname: "{{ hostname_output.stdout }}"
    oim_domain_name: "{{ domain_name_output.stdout }}"
    oim_ip_addresses: "{{ ip_output.stdout | regex_findall('inet\\s([0-9.]+)') }}"

- name: Include local_repo_access.yml
  ansible.builtin.include_vars: "{{ local_repo_access_path }}"
