# Copyright 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Set oim_os
  ansible.builtin.set_fact:
    oim_os: "{{ ansible_distribution | lower }}"

- name: Fetch oim details
  ansible.builtin.include_tasks: fetch_oim_details.yml

- name: Validate site_config.yml
  ansible.builtin.include_tasks: validate_site_config.yml

- name: Validate provision_config_credentials.yml
  ansible.builtin.include_tasks: validate_provision_config_credentials.yml

- name: Run prerequisite
  ansible.builtin.include_tasks: prereq_{{ ansible_distribution | lower }}.yml

- name: Enable buildkit
  ansible.builtin.include_tasks: enable_buildkit.yml

- name: Build vLLM from source
  ansible.builtin.include_tasks: vllm_source_build.yml

- name: Push vLLM to local repo
  ansible.builtin.include_tasks: vllm_local_repo_push.yml
