#  Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Intialize provision_password_status
  ansible.builtin.set_fact:
    provision_password_status: false

- name: Assert given root password
  block:
    - name: Assert given root password
      ansible.builtin.assert:
        that:
          - provision_password | length >= min_length
          - provision_password | length <= max_length
          - '"-" not in provision_password '
          - '"\\" not in provision_password '
          - '"\"" not in provision_password '
          - " \"'\" not in provision_password "
      no_log: true
  rescue:
    - name: Root password validation check
      ansible.builtin.fail:
        msg: "{{ provision_password_fail_msg }}"

- name: Set provision_password_status to true
  ansible.builtin.set_fact:
    provision_password_status: true
    provision_password: "{{ hostvars['127.0.0.1']['provision_password'] }}"

- name: Set passwordless SSH
  when: provision_password_status
  block:
    - name: Set Facts
      ansible.builtin.set_fact:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        ssh_key_status: false

    - name: Disable host key checking
      ansible.builtin.replace:
        path: "{{ ssh_config_path }}"
        regexp: '#   StrictHostKeyChecking ask'
        replace: 'StrictHostKeyChecking no'
      register: disable_host_key_checking
      connection: local

    - name: Disable strict mode checking
      ansible.builtin.replace:
        path: "{{ ssh_config_path }}"
        regexp: '^StrictModes\ '
        replace: 'StrictModes no'
      register: disable_strict_mode_checking
      connection: local

    - name: Restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted
      tags: skip_ansible_lint
      when:
        - disable_strict_mode_checking.changed or
          disable_host_key_checking.changed
      connection: local

    - name: Install sshpass
      ansible.builtin.package:
        name: sshpass
        state: present
      connection: local

    - name: Verify and set passwordless ssh from manager to compute nodes
      connection: local
      block:
        - name: Execute on individual hosts
          ansible.builtin.include_tasks: check_passwordless_ssh.yml
          with_items: "{{ ssh_to }}"
          loop_control:
            pause: 5
