# Copyright 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Get info for all Kubernetes services
  kubernetes.core.k8s_info:
    kind: Service
  register: svc_info

- name: Change svc type of LoadBalancer svcs to ClusterIP
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ item.metadata.name }}"
        namespace: "{{ item.metadata.namespace }}"
      spec:
        type: ClusterIP
  loop: "{{ svc_info.resources }}"
  when: item.spec.type == 'LoadBalancer' and item.metadata.name in ['grafana', 'timescaledb']
  no_log: true

- name: Delete metallb pools.yaml
  kubernetes.core.k8s:
    state: absent
    src: "{{ metallb_pools_path }}"

- name: Delete metallb layer2.yaml
  kubernetes.core.k8s:
    state: absent
    src: "{{ metallb_layer2_path }}"

- name: Delete metallb CRD
  kubernetes.core.k8s:
    state: absent
    src: "{{ metallb_crd_path }}"
