---
# tasks file for slurm
- name: Sync time
  ansible.builtin.include_tasks: time_sync.yml

- name: Install common packages
  ansible.builtin.package:
    name: "{{ common_packages[ansible_os_family] }}"
    state: present

- name: Firewall service running
  ansible.builtin.systemd_service:
    name: firewalld
    state: started
    enabled: true

- name: Create user and group
  ansible.builtin.include_tasks: _user.yml

- name: Create the slurm directory on share
  ansible.builtin.file:
    path: "{{ share_path }}/{{ slurm_dir_name }}"
    state: directory
    owner: root
    group: root
    mode: "{{ common_mode }}"

- name: Install and configure Munge
  ansible.builtin.include_tasks: _munge.yml

- name: Slurm dict ops
  ansible.builtin.set_fact:
    slurm_conf_dict: "{{ __slurm_default_config | ansible.builtin.combine(slurm_config | default({})) }}"
    cgroup_conf_dict: "{{ __cgroup_default_config | ansible.builtin.combine(cgroup | default({})) }}"
    slurm_dbd_conf_dict: "{{ __slurm_dbd_default_config | ansible.builtin.combine(slurm_dbd_config | default({})) }}"
