--- #db.yml TODO: Add ansible collection for mysql to omnia core list
# Needed?
# - name: Sync time
#   ansible.builtin.include_tasks: time_sync.yml

- name: Install db packages
  ansible.builtin.package:
    name: "{{ db_packages[ansible_os_family][db_type] }}"
    state: present 
  register: new_install

# Port Config
- name: Enable db port
  ansible.posix.firewalld:
    port: "{{ db_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true

- name: Enable and start the mysql service
  ansible.builtin.service:
    name: mysqld
    enabled: true
    state: started
  register: ctld_service
  when: db_type == 'mysql'

- name: Enable and start the mariadb service
  ansible.builtin.service:
    name: mariadb
    enabled: true
    state: started
  register: ctld_service
  when: db_type == 'mariadb'

- name: Add ansible db user
  community.mysql.mysql_user:
    login_user: "{{ db_username_default }}"
    login_password: "{{ db_password_default }}"
    name: "{{ db_username }}"
    password: "{{ db_password }}"
    host: "localhost"
    priv: '*.*:ALL,GRANT'
    login_unix_socket: /var/lib/mysql/mysql.sock
    state: present
  when: new_install.changed

- name: Add db user - shortname
  community.mysql.mysql_user:
    login_user: "{{ db_username }}"
    login_password: "{{ db_password }}"
    name: "{{ slurm_db_username }}"
    password: "{{ slurm_db_password }}"
    host: "{{ groups['slurm_dbd'][0] }}"
    priv: '*.*:ALL,GRANT'
    login_unix_socket: /var/lib/mysql/mysql.sock
    state: present

- name: Add db user - FQDN
  community.mysql.mysql_user:
    login_user: "{{ db_username }}"
    login_password: "{{ db_password }}"
    name: "{{ slurm_db_username }}"
    password: "{{ slurm_db_password }}"
    host: "{{ groups['slurm_dbd'][0] }}.%"
    priv: '*.*:ALL,GRANT'
    login_unix_socket: /var/lib/mysql/mysql.sock
    state: present

# TODO: Enable port 3306 in the mysqul.cnf file?