---
- name: Is db_host defined
  ansible.builtin.set_fact:
    db_host: "{{ groups['slurm_dbd'][0] }}"
  when: db_host is not defined and '"slurm_node" in group_names'

- name: Is db_port defined
  ansible.builtin.set_fact:
    db_port: "{{ db_port_default }}"
  when: db_port is not defined and '"slurm_node" in group_names'

- name: Set db_host
  ansible.builtin.set_fact:
    db_host: "{{ groups['slurm_dbd'][0] }}"
  when: db_host == None or db_host == "" and '"slurm_node" in group_names'

- name: Set db_port
  ansible.builtin.set_fact:
    db_port: "{{ db_port_default }}"
  when: db_port == None and '"slurm_node" in group_names'

- name: Create DB tasks
  ansible.builtin.include_tasks: db.yml
  args:
    apply:
        delegate_to: "{{ db_host }}"
  run_once: true

- name: Install DBD packages
  ansible.builtin.package:
    name: "{{ slurm_dbd_packages[ansible_os_family] }}"
    state: present

- name: Create files - {{ item }} # TODO: file required?
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    owner: "{{ slurm_user }}"
    group: "{{ slurm_user_group }}"
    mode: "{{ slurm_mode }}"
  loop:
    - "{{ slurm_dbd_conf_dict['LogFile'] }}"
    - "{{ slurm_dbd_conf_dict['PidFile'] }}"

# Port Config
- name: Enable SlurmdbdPort
  ansible.posix.firewalld:
    port: "{{ slurm_dbd_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true

# Edit service
- name: Enable the service
  ansible.builtin.service:
    name: slurmdbd
    enabled: true
  register: ctld_service

- name: Edit the service
  community.general.ini_file:
    path: "{{ ctld_service['status']['FragmentPath'] | default('/usr/lib/systemd/system/slurmdbd.service') }}"
    section: Unit
    option: ConditionPathExists
    value: "{{ slurm_share_prefix }}{{ slurm_config_dir }}/slurmdbd.conf"
    no_extra_spaces: true
  notify:
    - Reload slurmdbd
    - Restart slurmdbd