---
- name: Add nodes Slurm
  hosts: slurm_control_node, slurm_node, login, slurm_dbd
  any_errors_fatal: true
  vars:
    share_mounted_path: "{{ hostvars['localhost']['share_path'] | default('/home') }}" # from storage.yml
    #TODO: nfs_client role here, slurm depends on a mandatory share path
  pre_tasks:
    - name: Include input project directory
      ansible.builtin.import_role:
        name: ../utils/roles/include_input_dir
      run_once: true
      delegate_to: localhost
    - name: Include vars omnia_config.yml
      ansible.builtin.include_vars:
        file: "{{ input_project_dir }}/omnia_config.yml"
      run_once: true
      delegate_to: localhost
  tasks:
    - name: Add node
      ansible.builtin.import_role:
        name: slurm
        tasks_from: add_node
