---
- name: Add nodes Slurm
  hosts: slurm_control_node, slurm_node, login, slurm_dbd
  any_errors_fatal: true
  vars:
    cp_share_mounted_path: /opt/omnia
    share_mounted_path: /home
  pre_tasks:
    - name: Get the project input path
      ansible.builtin.set_fact:
        project_input_path: "{{ cp_share_mounted_path }}/input/{{ ( lookup('file', cp_share_mounted_path+'/input/default.yml') | from_yaml ).project_name | default('project_default') }}"
      run_once: true
      delegate_to: localhost
    - name: Include vars omnia.yml
      ansible.builtin.include_vars:
        file: "{{ project_input_path }}/omnia_config.yml"
      delegate_to: localhost
    - name: debug
      ansible.builtin.debug:
        var: slurm_installation_type
  # roles:
  #   - role: slurm
  tasks:
    - name: add node
      ansible.builtin.import_role:
        name: slurm
        tasks_from: add_node
