# yaml file contents
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data2-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  - ReadWriteMany
  nfs:
    server: 10.0.0.1
    path: /work/k8s/data2
  persistentVolumeReclaimPolicy: Recycle
  #storageClassName: local-storage
  #hostPath:
    #path: /home/k8s/
 
