---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data1-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  - ReadWriteMany
  nfs:
    server: 10.0.0.1
    path: /work/k8s/data1
  persistentVolumeReclaimPolicy: Recycle
 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data2-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  - ReadWriteMany
  nfs:
    server: 10.0.0.1
    path: /work/k8s/data2
  persistentVolumeReclaimPolicy: Recycle
 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data3-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  - ReadWriteMany
  nfs:
    server: 10.0.0.1
    path: /work/k8s/data3
  persistentVolumeReclaimPolicy: Recycle
 
