# yaml file contents
apiVersion: v1
kind: PersistentVolume
metadata:
  name: notebooks-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  - ReadWriteMany
  #persistentVolumeReclaimPolicy: Recycle
  #storageClassName: local-storage
  hostPath:
    path: /home/k8s/
 
