# yaml file contents
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  #- ReadWriteOnce
  #- ReadOnlyMany
  - ReadWriteMany
  nfs:
    server: 10.0.0.1
    path: /work/k8s
  #persistentVolumeReclaimPolicy: Recycle
  #storageClassName: local-storage
  #hostPath:
    #path: /home/k8s
 
