apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pets-pvc
  namespace: kubeflow
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
