#  Copyright 2024 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Install pmix packages ubuntu
  ansible.builtin.package:
    name: "{{ pmix_packages_ubuntu }}"
    state: present
  when: ansible_distribution | lower == 'ubuntu'
  tags: install

- name: Installs gcc/g++/cmake or gcc-c++ packages Ubuntu
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ gcc_package_names_ubuntu }}"
  when: ansible_distribution | lower == 'ubuntu'
  tags: install

- name: Install gcc packages redhat
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ gcc_package_names_redhat }}"
  when: ansible_distribution | lower is in ['redhat', 'rocky']
  tags: install

- name: Installs clang packages
  ansible.builtin.package:
    name: "{{ clang_package }}"
    state: present
