name: Ansible Lint

on:
  pull_request:
    branches:
      - main
      - release-1.7
      - staging
      - release-1.7.1
      - pub/new_architecture

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Modify ansible.cfg for linting
      #   run: |
      #     sed -i '/collections_path/d' ansible.cfg

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible and Ansible Lint
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Install Ansible Collections from requirements.yml
        run: |
          ansible-galaxy collection install -r .config/requirements.yml

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v25.1.3
        with:
          args: --config=.config/ansible-lint.yml

