# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

- name: Include roles_config.yml
  block:
    - name: Include roles_config.yml
      ansible.builtin.include_vars: "{{ roles_config_path }}"
      register: include_roles_config
      tags: init
  rescue:
    - name: Failed to include  roles_config.yml
      ansible.builtin.fail:
        msg: "{{ roles_config_syntax_fail_msg }} Error: {{ include_roles_config.message }}"

- name: Determine layer
  set_fact:
    layer: "{{ 'first' if 'first_layer' in ansible_run_tags else 'default' }}"

- name: Fetch composable roles data
  fetch_roles_config:
    roles_data: "{{ Roles }}"
    groups_data: "{{ Groups }}"
    mapping_file_path: "{{ pxe_mapping_file_path }}"
    layer: "{{ layer }}"
  register: composable_roles_output

- name: Set Facts for composable roles data
  ansible.builtin.set_fact:
    roles_data: "{{ composable_roles_output.roles_data }}"
    groups_data: "{{ composable_roles_output.groups_data }}"
    bmc_details: "{{ composable_roles_output.bmc_details }}"
    mapping_details: "{{ composable_roles_output.mapping_details }}"
    bmc_required: "{{ composable_roles_output.bmc_required }}"
    switch_required: "{{ composable_roles_output.switch_required }}"

- name: Show mapping setails
  ansible.builtin.debug:
    msg: "{{ mapping_details }}"

- name: Display filtered bmc details
  ansible.builtin.debug:
    msg: "{{ bmc_details }}"
  when: bmc_required

- name: Display all roles and groups
  ansible.builtin.debug:
    msg: "Groups: {{ groups_data }}, Roles: {{ roles_data }}"
